name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Adjust to your main branch name

env:
  REGISTRY: docker.io  # Replace with your container registry URL
  IMAGE_NAME: wisecow  # Replace with your Docker image name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin ${{ env.REGISTRY }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA


